# Makefile for FFT test drivers

SHELL = /bin/sh

# compiler/linker settings

CC =		CC
CCFLAGS =	-g -O3 $(PRECISION) -DFFT_INTEL_NO_TBB
LINK =		CC
LINKFLAGS =	-g -O

F90 = 		ftn
F90FLAGS =	-g -O3 -cpp $(PRECISION)
FLINK =		ftn
FLINKFLAGS =	-g -O

# memory, MPI, 1d FFT, precision settings

MEM_INC =	-DFFT_MEMALIGN=64

FFT_INC =       -I../src
FFT_PATH =      -L../src
FFT_LIB =       -lfft $(FFT1D)

EXTRA_INC =     $(MEM_INC) $(MPI_INC) $(FFT_INC)
EXTRA_PATH =    $(MPI_PATH) $(FFT_PATH)
EXTRA_LIB =     $(MPI_LIB) $(FFT_LIB)

p = 		DOUBLE
P =       	$(shell echo $(p) | tr a-z A-Z)

ifeq ($(P),SINGLE)
  PRECISION = -DFFT_SINGLE
else
  PRECISION = -DFFT_DOUBLE
endif

fft = 		KISS
FFT =		$(shell echo $(fft) | tr a-z A-Z)

ifeq ($(FFT),FFTW2)
  FFT1D = -lfftw
else ifeq ($(FFT),FFTW3)
  ifeq ($p,single)
    FFT1D = -lfftw3f
  else
    FFT1D = -lfftw3
  endif
else ifeq ($(FFT),FFTW)
  ifeq ($p,single)
    FFT1D = -lfftw3f
  else
    FFT1D = -lfftw3
  endif
else ifeq ($(FFT),MKL)
  ifeq ($c,intel)
    FFT1D = -lmkl_intel_lp64 -lmkl_sequential -lmkl_core
  else
    FFT1D = -lmkl_gf_lp64 -lmkl_sequential -lmkl_core
  endif
else
  FFT1D =
endif

# targets

all:	clean test3d test2d test3d_c test2d_c test3d_f90 test2d_f90

test3d:	test3d.o
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) test3d.o $(EXTRA_LIB) -o test3d

test2d:	test2d.o
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) test2d.o $(EXTRA_LIB) -o test2d

test3d_c:	test3d_c.o
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) test3d_c.o $(EXTRA_LIB) -o test3d_c

test2d_c:	test2d_c.o
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) test2d_c.o $(EXTRA_LIB) -o test2d_c

test3d_f90:	test3d_f90.o
	$(FLINK) $(FLINKFLAGS) $(EXTRA_PATH) test3d_f90.o $(EXTRA_LIB) \
	-lstdc++ -o test3d_f90

test2d_f90:	test2d_f90.o
	$(FLINK) $(FLINKFLAGS) $(EXTRA_PATH) test2d_f90.o $(EXTRA_LIB) \
	-lstdc++ -o test2d_f90

clean:
	@rm -f *.o *.mod test3d test2d test3d_c test2d_c test3d_f90 test2d_f90

# rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.o:%.f90
	$(F90) $(F90FLAGS) $(EXTRA_INC) -c $<
